blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/K4ryuu/CS2-Egg/tree/dev/docs
    about: Read the comprehensive documentation
  - name: ðŸ’¬ Discussions
    url: https://github.com/K4ryuu/CS2-Egg/discussions
    about: Ask questions and discuss with the community
